#Front-end
FROM node:lts-alpine3.12 as build
WORKDIR /front-end
COPY package*.json /front-end/
RUN npm i 
COPY . /front-end/
RUN npm run build

#Hosting
FROM nginx:stable-alpine
RUN rm -rf /usr/share/nginx/html/* && rm -rf /etc/nginx/nginx.conf
COPY ./nginx.conf /etc/nginx/nginx.conf
COPY --from=build /front-end/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
